### PR TITLE
Make mkdir and touch safe and without surprises

### PR DESCRIPTION
**Pull request by tomsmeding**
This 1. makes mkdir and touch safe against shell injection vulnerabilities,
and 2. still allows the user to create any kind of file or directory.

This would fix my #33 I think.

### CODE REVIEW

**Comment by tomsmeding** [comment]
Sorry, this doesn't make sense at all. Will fix, hang on...

**Comment by tomsmeding** [comment]
This should work, and still allow any name to be specified (including slashes etc.)

**Comment by shyguy** [comment]
Possibly conflicting with #37, although #37 looks a little cleaner.

**Comment by lieuwex** [comment]
@shyguy This PR seems to allow spaces and other special characters in the name of files. #37 seems not to.

**Comment by shyguy** [comment]
Ah yes, I didn't pay enough attention to that. It's up to @eriksvedang to decide which he likes better. I personally think that the shell-quote function would use useful as part of the standard library even, or for other internal functions that use the shell.

**Comment by eriksvedang** [comment]
Looks great, I'll compare the solutions and merge when I'm back at my work computer after the weekend.

**Comment by mkfifo** [comment]
As author of #37 I think this (#43) is better, assuming it is safe.

I think it captures all the cases that are obviously dangerous.

**Comment by tomsmeding** [comment]
@mkfifo: Thanks, and I definitely agree that calling a shell routine should be preceded by correct escaping/quoting/etc. My point, which I'm going to repeat here again (at the risk of becoming annoying...), is that I feel like *these routines should not be like shell routines to the programmer*. They might use the shell, but to the user they must be normal functions like any other.
</annoy>

I've finally gotten around to cloning the repo and playing around with it, as you've noticed, and I like this idea very much. Please continue developing this!

**Comment by mkfifo** [comment]
@tomsmeding I wasn't making that comment to you in particular, I just wanted to make sure people understood the risks.
I also agree these should appear like normal functions, and their implementation should be hidden behind the interface.

Therefore this function should deal with any escaping specific to the implementation (in this case - the shell), and the caller should be responsible for general user input validation/scrubbing.

I also think that my iffyness around special characters is not a programming-level concern, and as mentioned in the earlier thread I was hoping to eventually add quoting in, so I think this (#43) is a better approach.

So I think we should merge this (#43) instead - and close my earlier work #37.

**Comment by mkfifo** [comment]
@tomsmeding thanks!

**Comment by tomsmeding** [comment]
@mkfifo No problem :)

**Pull request merged**
