### PR TITLE
adding blank lines in RESEARCH.md for better markdown formatting

### PR DESCRIPTION
**Pull request by mkfifo**
Markdown will squash adjacent lines into a single sentence/paragraph, blank lines between them will prevent this.

See the current formatting of
https://github.com/eriksvedang/Carp/blob/master/RESEARCH.md
which often has multiple links on the same line, and with word-wrapping.

and compare it to
https://github.com/mkfifo/Carp/blob/research-markdown-formatting/RESEARCH.md
which has a single link per line.

We could alternatively add in some html `<br />`, or format it as a mark-down list by prefixing each line with ` -`.
But this proposed solution has the advantage of the file still being easy to treat as plain-text.

### CODE REVIEW

**Comment by eriksvedang** [comment]
Oh, I usually just read the file in my text editor so that's why I haven't cared about this. Maybe making them bullet points would work better for both situations?

**Comment by mkfifo** [comment]
okay, will make that change now

**Comment by mkfifo** [comment]
Done, please see https://github.com/mkfifo/Carp/blob/research-markdown-formatting/RESEARCH.md

**Comment by eriksvedang** [comment]
Excellent!

**Comment by mkfifo** [comment]
Thanks :)

**Pull request merged**
